### ISSUE TITLE
Performance Chart

### ISSUE THREAD

**Issue by elimelt** [hcp-uw/syntext#28]

**Comment by karhu1** [comment]
### Progress Update:

1. Added functioning data gathered from user input to display correctly on the graph.
2. Implemented restart button functionality so that users can go back to typing screen from game summary.
3. Added a working calculation of accuracy and made it display on the page.

### Undone Tasks:

1. Create an overall words per minute and display it on the game summary
2. Create a working version of "next snippet" button, or more functionality to the game summary page in general.

**Comment by elimelt** [comment]
looks good!

as you mentioned above, the new snippet button doesn't currently work, nor do any of the snippet option buttons after the game summary is displayed.

This is simply because there are no props being passed to GameOptions when rendered with the GameSummary component. 

![image](https://user-images.githubusercontent.com/98496503/229348588-f1a9ae8e-cbdd-4d2b-9944-f770f7fd4d41.png)
![image](https://user-images.githubusercontent.com/98496503/229348599-f5c22467-1ba5-4821-8fe5-d17909471ada.png)

If you copy and past all of the props from the first instance of GameOptions to the second, then the buttons in GameOptions should work just fine!

**Comment by karhu1** [comment]
### Progress Update:

- Added a working WPM average to the game summary page. 

### Undone Tasks:

- Still need to revamp for better functionality, but Elijah's suggestion will help for now.

**Comment by elimelt** [comment]
I am going to close this issue as it seems to be working in its current form pretty well
