### ISSUE TITLE
snippet completion

### ISSUE THREAD

**Issue by kaitinderr** [hcp-uw/syntext#54]
Currently, the user has to hit enter once they finish typing in order to actually "finish" the snippet and see statistics. This should be changed so they are sent to statistics as soon as they finish typing the snippet, removing the need to hit enter.

**Comment by karhu1** [comment]
A way to combat this is to use what we already have written for the enter key handler:

![image](https://user-images.githubusercontent.com/107146650/233186774-7ce17271-8785-4d0a-936f-bc5cdf06c124.png)

Instead of handling it inside of handleSpecialKey, switch it to handleChange but copy over the checkers (minus the enter key). Maybe now create some way to check if we're typing on the last line, and you should be good!

![image](https://user-images.githubusercontent.com/107146650/233186687-81e85798-ebd3-46a6-8193-405d651ebd66.png)

**Comment by elimelt** [comment]
@kaitinderr any updates?

**Comment by kaitinderr** [comment]
@elimelt completed!
